"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

import AuthProvider from "@/context/authProvider";
import { signOut } from "next-auth/react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          {children}
          <Toaster />

          <button
            onClick={() => {
              signOut({ callbackUrl: "/signin" });
            }}
            className="text-black"
          >
            logggout
          </button>
        </body>
      </AuthProvider>
    </html>
  );
}
